//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EastFive.Azure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EastFive.Azure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;accountEnabled&quot;: true,
        ///  &quot;creationType&quot;: &quot;LocalAccount&quot;,
        ///  &quot;displayName&quot;: &quot;{2}&quot;,
        ///  &quot;passwordProfile&quot;: {
        ///    &quot;password&quot;: &quot;{1}&quot;,
        ///    &quot;forceChangePasswordNextLogin&quot;: false
        ///  },
        ///  &quot;signInNames&quot;: [
        ///    {
        ///      &quot;type&quot;: &quot;emailAddress&quot;,
        ///      &quot;value&quot;: &quot;{0}&quot;
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string b2c_graphclient_user_post_email {
            get {
                return ResourceManager.GetString("b2c_graphclient_user_post_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head id=&quot;head&quot;&gt;&lt;/head&gt;
        ///&lt;body id=&quot;body&quot; class=&quot;hold-transition sidebar-mini fixed&quot;&gt;
        ///        &lt;script&gt;
        ///
        ///            function loadScript(bodyElement, url, callback) {
        ///                var script = document.createElement(&quot;script&quot;);
        ///                script.type = &quot;text/javascript&quot;;
        ///                if (script.readyState) {  //IE
        ///                    script.onreadystatechange = function () {
        ///                        if (script.readyState === &quot;loaded&quot; || script.readyState === &quot;complete [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string indexPage {
            get {
                return ResourceManager.GetString("indexPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dash-root&gt;&lt;/dash-root&gt;&lt;script type=&quot;text/javascript&quot; src=&quot;inline.54c1233f72172d979b96.bundle.js&quot;&gt;&lt;/script&gt;&lt;script type=&quot;text/javascript&quot; src=&quot;polyfills.d9faed5c4d2817543fd2.bundle.js&quot;&gt;&lt;/script&gt;&lt;script type=&quot;text/javascript&quot; src=&quot;scripts.02bf58f26e3bc6f16cdb.bundle.js&quot;&gt;&lt;/script&gt;&lt;script type=&quot;text/javascript&quot; src=&quot;main.6d7888cd63472334f6ce.bundle.js&quot;&gt;&lt;/script&gt;.
        /// </summary>
        internal static string spabody {
            get {
                return ResourceManager.GetString("spabody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;meta charset=&quot;utf-8&quot;&gt;&lt;title&gt;Dash&lt;/title&gt;&lt;base href=&quot;/&quot;&gt;&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1&quot;&gt;&lt;link rel=&quot;icon&quot; type=&quot;image/x-icon&quot; href=&quot;favicon.ico&quot;&gt;&lt;link href=&quot;styles.0bc98765f532baaa7699.bundle.css&quot; rel=&quot;stylesheet&quot;/&gt;.
        /// </summary>
        internal static string spahead {
            get {
                return ResourceManager.GetString("spahead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;&lt;html lang=&quot;en&quot; data.ie=&quot;isloading&quot;&gt;&lt;head&gt;&lt;meta charset=&quot;utf-8&quot;&gt;&lt;title&gt;Dash&lt;/title&gt;&lt;base href=&quot;/&quot;&gt;&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1&quot;&gt;&lt;link rel=&quot;icon&quot; type=&quot;image/x-icon&quot; href=&quot;favicon.ico&quot;&gt;&lt;link href=&quot;styles.0bc98765f532baaa7699.bundle.css&quot; rel=&quot;stylesheet&quot;/&gt;&lt;/head&gt;&lt;body class=&quot;hold-transition sidebar-mini fixed&quot;&gt;&lt;dash-root&gt;&lt;/dash-root&gt;&lt;script type=&quot;text/javascript&quot; src=&quot;inline.54c1233f72172d979b96.bundle.js&quot;&gt;&lt;/script&gt;&lt;script type=&quot;text/javascript&quot; src=&quot;polyfil [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spahtml {
            get {
                return ResourceManager.GetString("spahtml", resourceCulture);
            }
        }
    }
}
